### ISSUE TITLE
Possible run Ios safari?

### ISSUE THREAD

**Issue by namnn89** [willianjusten/awesome-audio-visualization#13]
With audio visualization. Can I use source run on safari on iOS?

**Comment by willianjusten** [comment]
Sorry @namnn89 , but I didn't understand your question, can you explain more?

**Comment by namnn89** [comment]
i need audio visualization.
such as http://wayou.github.io/HTML5_Audio_Visualizer/
but it is not working on Safari (Ios)

**Comment by willianjusten** [comment]
If you take a look at [can I use](http://caniuse.com/#search=audio%20api), Safari allows to use Web Audio API, but you need to pay attention to some details, you can't play automatically, the user needs to allow this.

Another thing is about how you're working in your music, you need to create a buffer to your music to make sure that everything works and then play.

**[See this one](http://codepen.io/noeldelgado/pen/EaNjBy)**
