### ISSUE TITLE
Compatibilidade com React Native

### ISSUE THREAD

**Issue by wesleymonaro** [willianjusten/awesome-audio-visualization#33]
Fala @willianjusten 

Saberia me dizer se de alguma forma eu consigo usar o audioviz no React Native? A minha ideia é usar o audioviz com o microfone do smartphone. A questão nem é tanto o canvas, mas sim o objeto Audio. No RN não permite instanciar um new Audio() :(

Obrigado!

**Comment by willianjusten** [comment]
Opa, eu infelizmente nunca trabalhei com Native, então realmente não sei dizer =/

**Comment by wesleymonaro** [comment]
Entendi Wilian, beleza! Vou procurar soluções aqui, se encontrar algo posto aqui ;)

Valeu!

**Comment by willianjusten** [comment]
Show, vou só fechar a issue por enquanto, já que não é 100% relacionada a lista.
