### ISSUE TITLE
Permission to push a new branch

### ISSUE THREAD

**Issue by danielbarion** [willianjusten/awesome-audio-visualization#39]
Hi guys,

Eu gostaria de fazer um pull request para adicionar o seguinte projeto a lista:
- [React Player](https://dazzling-jang-471a34.netlify.com/) - A complete Audio Visualisation player with ReactJS.

Clonei o repositório -> criei uma nova branch -> adicionei meu projeto a lista -> commitei -> tentei dar push para fazer o PR mas recebi o erro de permissão insuficiente;

**Comment by willianjusten** [comment]
A forma correta é ao invés de clonar é forkar. Aí você consegue fazer Pull Request do Fork para cá.

**Comment by willianjusten** [comment]
Dá uma lida nesse artigo e segue ele:

https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/

**Comment by danielbarion** [comment]
Entendi,

Muito obrigado!
